'use client';

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { AdminInput, AdminPageHeader, EmptyState, ErrorState, LoadingState } from '../../../../components/admin/AdminShared';
import { createAdminAuthor, fetchAdminAuthors, updateAdminAuthor, type AdminAuthor } from '../../../../services/admin';

export default function AuthorsPage() {
  const [authors, setAuthors] = useState<AdminAuthor[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [name, setName] = useState('');
  const [bio, setBio] = useState('');
  const [avatarUrl, setAvatarUrl] = useState('');
  const [saving, setSaving] = useState(false);

  const load = () => {
    setLoading(true);
    fetchAdminAuthors()
      .then(setAuthors)
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
  }, []);

  const create = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    setSaving(true);
    try {
      const created = await createAdminAuthor({
        name: name.trim(),
        bio: bio.trim() || undefined,
        avatarUrl: avatarUrl.trim() || undefined,
      });
      setAuthors((list) => [...list, created].sort((a, b) => a.name.localeCompare(b.name)));
      setName('');
      setBio('');
      setAvatarUrl('');
      toast.success('Author created.');
    } catch {
      toast.error('Could not create the author.');
    } finally {
      setSaving(false);
    }
  };

  const saveBio = async (author: AdminAuthor, nextBio: string) => {
    try {
      const updated = await updateAdminAuthor(author.id, { bio: nextBio });
      setAuthors((list) => list.map((item) => (item.id === author.id ? updated : item)));
      toast.success('Author updated.');
    } catch {
      toast.error('Could not update the author.');
    }
  };

  return (
    <div className="space-y-6">
      <AdminPageHeader title="Authors" subtitle="Editorial bylines used by news articles. Slugs are generated by the API." />

      <form onSubmit={create} className="grid gap-3 rounded-lg p-4 sm:grid-cols-2" style={{ border: '1px solid var(--admin-border)', background: 'var(--admin-card)' }}>
        <AdminInput value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" required />
        <AdminInput value={avatarUrl} onChange={(e) => setAvatarUrl(e.target.value)} placeholder="Avatar URL" />
        <div className="sm:col-span-2">
          <AdminInput value={bio} onChange={(e) => setBio(e.target.value)} placeholder="Short bio" />
        </div>
        <button type="submit" disabled={saving} className="rounded-md px-3 py-2 text-xs font-bold text-white disabled:opacity-60" style={{ background: 'var(--admin-accent)' }}>
          Create author
        </button>
      </form>

      {loading ? (
        <LoadingState />
      ) : error ? (
        <ErrorState message="Could not load authors." onRetry={load} />
      ) : authors.length === 0 ? (
        <EmptyState title="No authors yet" message="Create an editorial author to attach to articles." />
      ) : (
        <div className="space-y-3">
          {authors.map((author) => (
            <div key={author.id} className="rounded-lg p-4" style={{ border: '1px solid var(--admin-border)', background: 'var(--admin-card)' }}>
              <p className="text-sm font-semibold" style={{ color: 'var(--admin-text)' }}>{author.name}</p>
              <p className="text-xs" style={{ color: 'var(--admin-text-muted)' }}>{author.slug}</p>
              <AdminInput
                defaultValue={author.bio || ''}
                className="mt-2"
                onBlur={(e) => {
                  if (e.target.value !== (author.bio || '')) saveBio(author, e.target.value);
                }}
              />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
