'use client';

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { FileEdit, PenLine, X } from 'lucide-react';
import {
  AdminAvatar,
  AdminInput,
  AdminPageHeader,
  EmptyState,
  ErrorState,
  LoadingState,
} from '../../../../components/admin/AdminShared';
import MediaPicker from '../../../../components/admin/MediaPicker';
import { createAdminAuthor, fetchAdminAuthors, updateAdminAuthor, type AdminAuthor } from '../../../../services/admin';

const emptyForm = { name: '', bio: '', avatarUrl: '' };

export default function AuthorsPage() {
  const [authors, setAuthors] = useState<AdminAuthor[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [editing, setEditing] = useState<AdminAuthor | null>(null);
  const [saving, setSaving] = useState(false);
  const [galleryOpen, setGalleryOpen] = useState(false);

  const load = () => {
    setLoading(true);
    setError(false);
    fetchAdminAuthors()
      .then(setAuthors)
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
  }, []);

  const setField = (key: keyof typeof emptyForm, value: string) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const startEdit = (author: AdminAuthor) => {
    setEditing(author);
    setForm({
      name: author.name,
      bio: author.bio || '',
      avatarUrl: author.avatarUrl || '',
    });
  };

  const cancelEdit = () => {
    setEditing(null);
    setForm(emptyForm);
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name.trim()) return;
    setSaving(true);
    const payload = {
      name: form.name.trim(),
      bio: form.bio.trim() || undefined,
      avatarUrl: form.avatarUrl.trim() || undefined,
    };
    try {
      if (editing) {
        const updated = await updateAdminAuthor(editing.id, payload);
        setAuthors((list) => list.map((item) => (item.id === editing.id ? updated : item)).sort((a, b) => a.name.localeCompare(b.name)));
        toast.success('Author updated.');
        cancelEdit();
      } else {
        const created = await createAdminAuthor(payload);
        setAuthors((list) => [...list, created].sort((a, b) => a.name.localeCompare(b.name)));
        setForm(emptyForm);
        toast.success('Author created.');
      }
    } catch {
      toast.error(editing ? 'Could not update the author.' : 'Could not create the author.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-5">
      <AdminPageHeader title="Authors" subtitle="Editorial bylines used by news articles. Slugs are generated by the API." />

      <form
        onSubmit={submit}
        className="grid gap-3 rounded-lg p-4 sm:grid-cols-2"
        style={{ border: '1px solid var(--admin-border)', background: 'var(--admin-card)' }}
      >
        {editing && (
          <p className="text-xs font-semibold sm:col-span-2" style={{ color: 'var(--admin-text-secondary)' }}>
            Editing {editing.name}
          </p>
        )}
        <AdminInput value={form.name} onChange={(e) => setField('name', e.target.value)} placeholder="Name" required />
        <div className="flex gap-2">
          <AdminInput value={form.avatarUrl} onChange={(e) => setField('avatarUrl', e.target.value)} placeholder="Avatar URL" />
          <button
            type="button"
            onClick={() => setGalleryOpen(true)}
            className="shrink-0 rounded-md px-3 text-xs font-bold"
            style={{ border: '1px solid var(--admin-border)', color: 'var(--admin-accent)' }}
          >
            Gallery
          </button>
        </div>
        <div className="sm:col-span-2">
          <AdminInput value={form.bio} onChange={(e) => setField('bio', e.target.value)} placeholder="Short bio" />
        </div>
        <div className="flex flex-wrap items-center gap-2 sm:col-span-2">
          <button
            type="submit"
            disabled={saving}
            className="inline-flex items-center justify-center gap-2 rounded-md px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"
            style={{ background: 'var(--admin-accent)' }}
          >
            <PenLine size={15} />
            {editing ? 'Save author' : 'Create author'}
          </button>
          {editing && (
            <button
              type="button"
              onClick={cancelEdit}
              className="inline-flex items-center justify-center gap-2 rounded-md px-4 py-2.5 text-sm font-semibold"
              style={{ color: 'var(--admin-text-secondary)', border: '1px solid var(--admin-border)' }}
            >
              <X size={15} />
              Cancel
            </button>
          )}
        </div>
      </form>

      {loading ? (
        <LoadingState />
      ) : error ? (
        <ErrorState message="Could not load authors." onRetry={load} />
      ) : authors.length === 0 ? (
        <EmptyState icon={<PenLine size={28} />} title="No authors yet" message="Create an editorial author to attach to articles." />
      ) : (
        <div className="overflow-hidden rounded-lg" style={{ border: '1px solid var(--admin-border)', background: 'var(--admin-card)' }}>
          <table className="w-full text-left text-sm">
            <thead>
              <tr style={{ background: 'var(--admin-table-header)', borderBottom: '1px solid var(--admin-border)' }}>
                <th className="px-4 py-3 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Author</th>
                <th className="px-4 py-3 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Slug</th>
                <th className="px-4 py-3 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Bio</th>
                <th className="px-4 py-3 text-right text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {authors.map((author) => (
                <tr
                  key={author.id}
                  style={{
                    borderBottom: '1px solid var(--admin-border)',
                    background: editing?.id === author.id ? 'var(--admin-table-row-hover)' : 'transparent',
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--admin-table-row-hover)'; }}
                  onMouseLeave={(e) => { e.currentTarget.style.background = editing?.id === author.id ? 'var(--admin-table-row-hover)' : 'transparent'; }}
                >
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3">
                      <AdminAvatar name={author.name} src={author.avatarUrl} size={36} />
                      <p className="font-semibold" style={{ color: 'var(--admin-text)' }}>{author.name}</p>
                    </div>
                  </td>
                  <td className="px-4 py-3 font-mono text-xs" style={{ color: 'var(--admin-text-muted)' }}>{author.slug}</td>
                  <td className="max-w-xs px-4 py-3 text-sm" style={{ color: 'var(--admin-text-secondary)' }}>
                    {author.bio || '—'}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center justify-end">
                      <button
                        type="button"
                        onClick={() => startEdit(author)}
                        className="grid h-8 w-8 place-items-center rounded-md"
                        style={{ background: 'rgba(0, 191, 255, 0.14)', color: 'var(--admin-accent)' }}
                        title="Edit author"
                      >
                        <FileEdit size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <MediaPicker
        open={galleryOpen}
        title="Choose author avatar"
        onClose={() => setGalleryOpen(false)}
        onSelect={(url) => {
          setField('avatarUrl', url);
          setGalleryOpen(false);
        }}
      />
    </div>
  );
}
