'use client';

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { PenLine } from 'lucide-react';
import {
  AdminAvatar,
  AdminInput,
  AdminPageHeader,
  EmptyState,
  ErrorState,
  LoadingState,
} from '../../../../components/admin/AdminShared';
import { createAdminAuthor, fetchAdminAuthors, updateAdminAuthor, type AdminAuthor } from '../../../../services/admin';

export default function AuthorsPage() {
  const [authors, setAuthors] = useState<AdminAuthor[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [name, setName] = useState('');
  const [bio, setBio] = useState('');
  const [avatarUrl, setAvatarUrl] = useState('');
  const [saving, setSaving] = useState(false);

  const load = () => {
    setLoading(true);
    fetchAdminAuthors()
      .then(setAuthors)
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
  }, []);

  const create = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    setSaving(true);
    try {
      const created = await createAdminAuthor({
        name: name.trim(),
        bio: bio.trim() || undefined,
        avatarUrl: avatarUrl.trim() || undefined,
      });
      setAuthors((list) => [...list, created].sort((a, b) => a.name.localeCompare(b.name)));
      setName('');
      setBio('');
      setAvatarUrl('');
      toast.success('Author created.');
    } catch {
      toast.error('Could not create the author.');
    } finally {
      setSaving(false);
    }
  };

  const saveBio = async (author: AdminAuthor, nextBio: string) => {
    try {
      const updated = await updateAdminAuthor(author.id, { bio: nextBio });
      setAuthors((list) => list.map((item) => (item.id === author.id ? updated : item)));
      toast.success('Author updated.');
    } catch {
      toast.error('Could not update the author.');
    }
  };

  return (
    <div className="space-y-5">
      <AdminPageHeader title="Authors" subtitle="Editorial bylines used by news articles. Slugs are generated by the API." />

      <form
        onSubmit={create}
        className="grid gap-3 rounded-lg p-4 sm:grid-cols-2"
        style={{ border: '1px solid var(--admin-border)', background: 'var(--admin-card)' }}
      >
        <AdminInput value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" required />
        <AdminInput value={avatarUrl} onChange={(e) => setAvatarUrl(e.target.value)} placeholder="Avatar URL" />
        <div className="sm:col-span-2">
          <AdminInput value={bio} onChange={(e) => setBio(e.target.value)} placeholder="Short bio" />
        </div>
        <button
          type="submit"
          disabled={saving}
          className="inline-flex items-center justify-center gap-2 rounded-md px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60 sm:w-fit"
          style={{ background: 'var(--admin-accent)' }}
        >
          <PenLine size={15} />
          Create author
        </button>
      </form>

      {loading ? (
        <LoadingState />
      ) : error ? (
        <ErrorState message="Could not load authors." onRetry={load} />
      ) : authors.length === 0 ? (
        <EmptyState icon={<PenLine size={28} />} title="No authors yet" message="Create an editorial author to attach to articles." />
      ) : (
        <div className="overflow-hidden rounded-lg" style={{ border: '1px solid var(--admin-border)', background: 'var(--admin-card)' }}>
          <table className="w-full text-left text-sm">
            <thead>
              <tr style={{ background: 'var(--admin-table-header)', borderBottom: '1px solid var(--admin-border)' }}>
                <th className="px-4 py-3 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Author</th>
                <th className="px-4 py-3 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Slug</th>
                <th className="px-4 py-3 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--admin-text-secondary)' }}>Bio</th>
              </tr>
            </thead>
            <tbody>
              {authors.map((author) => (
                <tr
                  key={author.id}
                  style={{ borderBottom: '1px solid var(--admin-border)' }}
                  onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--admin-table-row-hover)'; }}
                  onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
                >
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3">
                      <AdminAvatar name={author.name} src={author.avatarUrl} size={36} />
                      <p className="font-semibold" style={{ color: 'var(--admin-text)' }}>{author.name}</p>
                    </div>
                  </td>
                  <td className="px-4 py-3 font-mono text-xs" style={{ color: 'var(--admin-text-muted)' }}>{author.slug}</td>
                  <td className="px-4 py-3">
                    <AdminInput
                      defaultValue={author.bio || ''}
                      placeholder="Add a short bio"
                      onBlur={(e) => {
                        if (e.target.value !== (author.bio || '')) saveBio(author, e.target.value);
                      }}
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
